# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from service.model import object_detection_pb2 as service_dot_model_dot_object__detection__pb2


class DetectStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.detect = channel.unary_unary(
        '/Detect/detect',
        request_serializer=service_dot_model_dot_object__detection__pb2.ObjectDetectionRequest.SerializeToString,
        response_deserializer=service_dot_model_dot_object__detection__pb2.Result.FromString,
        )


class DetectServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def detect(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DetectServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'detect': grpc.unary_unary_rpc_method_handler(
          servicer.detect,
          request_deserializer=service_dot_model_dot_object__detection__pb2.ObjectDetectionRequest.FromString,
          response_serializer=service_dot_model_dot_object__detection__pb2.Result.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Detect', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
