registry = {
    "image_recon_service": {
        "grpc": 7003,
    }
}

flowers_map_names = {
    0: "pink primrose",
    1: "hard-leaved pocket orchid",
    2: "canterbury bells",
    3: "sweet pea",
    4: "english marigold",
    5: "tiger lily",
    6: "moon orchid",
    7: "bird of paradise",
    8: "monkshood",
    9: "globe thistle",
    10: "snapdragon",
    11: "colt's foot",
    12: "king protea",
    13: "spear thistle",
    14: "yellow iris",
    15: "globe-flower",
    16: "purple coneflower",
    17: "peruvian lily",
    18: "balloon flower",
    19: "giant white arum lily",
    20: "fire lily",
    21: "pincushion flower",
    22: "fritillary",
    23: "red ginger",
    24: "grape hyacinth",
    25: "corn poppy",
    26: "prince of wales feathers",
    27: "stemless gentian",
    28: "artichoke",
    29: "sweet william",
    30: "carnation",
    31: "garden phlox",
    32: "love in the mist",
    33: "mexican aster",
    34: "alpine sea holly",
    35: "ruby-lipped cattleya",
    36: "cape flower",
    37: "great masterwort",
    38: "siam tulip",
    39: "lenten rose ",
    40: "barbeton daisy",
    41: "daffodil",
    42: "sword lily",
    43: "poinsettia",
    44: "bolero deep blue",
    45: "wallflower",
    46: "marigold",
    47: "buttercup",
    48: "oxeye daisy",
    49: "common dandelion",
    50: "petunia",
    51: "wild pansy",
    52: "primula",
    53: "sunflower",
    54: "pelargonium",
    55: "bishop of llandaff",
    56: "gaura",
    57: "geranium",
    58: "orange dahlia",
    59: "pink-yellow dahlia",
    60: "cautleya spicata",
    61: "japanese anemone",
    62: "black-eyed susan",
    63: "silverbush",
    64: "californian poppy",
    65: "osteospermum",
    66: "spring crocus",
    67: "bearded iris",
    68: "windflower",
    69: "tree poppy",
    70: "gazania",
    71: "azalea",
    72: "water lily",
    73: "rose",
    74: "thorn apple",
    75: "morning glory",
    76: "passion flower",
    77: "lotus",
    78: "toad lily",
    79: "anthurium",
    80: "frangipani",
    81: "clematis",
    82: "hibiscus",
    83: "columbine",
    84: "desert-rose",
    85: "tree mallow",
    86: "magnolia",
    87: "cyclamen",
    88: "watercress",
    89: "canna lily",
    90: "hippeastrum",
    91: "bee balm",
    92: "ball moss",
    93: "foxglove",
    94: "bougainvillea",
    95: "camellia",
    96: "mallow",
    97: "mexican petunia",
    98: "bromelia",
    99: "blanket flower",
    100: "trumpet creeper",
    101: "blackberry lily",
}

dogs_map_names = {
    0: "Affenpinscher",
    1: "Afghan_hound",
    2: "Airedale_terrier",
    3: "Akita",
    4: "Alaskan_malamute",
    5: "American_eskimo_dog",
    6: "American_foxhound",
    7: "American_staffordshire_terrier",
    8: "American_water_spaniel",
    9: "Anatolian_shepherd_dog",
    10: "Australian_cattle_dog",
    11: "Australian_shepherd",
    12: "Australian_terrier",
    13: "Basenji",
    14: "Basset_hound",
    15: "Beagle",
    16: "Bearded_collie",
    17: "Beauceron",
    18: "Bedlington_terrier",
    19: "Belgian_malinois",
    20: "Belgian_sheepdog",
    21: "Belgian_tervuren",
    22: "Bernese_mountain_dog",
    23: "Bichon_frise",
    24: "Black_and_tan_coonhound",
    25: "Black_russian_terrier",
    26: "Bloodhound",
    27: "Bluetick_coonhound",
    28: "Border_collie",
    29: "Border_terrier",
    30: "Borzoi",
    31: "Boston_terrier",
    32: "Bouvier_des_flandres",
    33: "Boxer",
    34: "Boykin_spaniel",
    35: "Briard",
    36: "Brittany",
    37: "Brussels_griffon",
    38: "Bull_terrier",
    39: "Bulldog",
    40: "Bullmastiff",
    41: "Cairn_terrier",
    42: "Canaan_dog",
    43: "Cane_corso",
    44: "Cardigan_welsh_corgi",
    45: "Cavalier_king_charles_spaniel",
    46: "Chesapeake_bay_retriever",
    47: "Chihuahua",
    48: "Chinese_crested",
    49: "Chinese_shar-pei",
    50: "Chow_chow",
    51: "Clumber_spaniel",
    52: "Cocker_spaniel",
    53: "Collie",
    54: "Curly-coated_retriever",
    55: "Dachshund",
    56: "Dalmatian",
    57: "Dandie_dinmont_terrier",
    58: "Doberman_pinscher",
    59: "Dogue_de_bordeaux",
    60: "English_cocker_spaniel",
    61: "English_setter",
    62: "English_springer_spaniel",
    63: "English_toy_spaniel",
    64: "Entlebucher_mountain_dog",
    65: "Field_spaniel",
    66: "Finnish_spitz",
    67: "Flat-coated_retriever",
    68: "French_bulldog",
    69: "German_pinscher",
    70: "German_shepherd_dog",
    71: "German_shorthaired_pointer",
    72: "German_wirehaired_pointer",
    73: "Giant_schnauzer",
    74: "Glen_of_imaal_terrier",
    75: "Golden_retriever",
    76: "Gordon_setter",
    77: "Great_dane",
    78: "Great_pyrenees",
    79: "Greater_swiss_mountain_dog",
    80: "Greyhound",
    81: "Havanese",
    82: "Ibizan_hound",
    83: "Icelandic_sheepdog",
    84: "Irish_red_and_white_setter",
    85: "Irish_setter",
    86: "Irish_terrier",
    87: "Irish_water_spaniel",
    88: "Irish_wolfhound",
    89: "Italian_greyhound",
    90: "Japanese_chin",
    91: "Keeshond",
    92: "Kerry_blue_terrier",
    93: "Komondor",
    94: "Kuvasz",
    95: "Labrador_retriever",
    96: "Lakeland_terrier",
    97: "Leonberger",
    98: "Lhasa_apso",
    99: "Lowchen",
    100: "Maltese",
    101: "Manchester_terrier",
    102: "Mastiff",
    103: "Miniature_schnauzer",
    104: "Neapolitan_mastiff",
    105: "Newfoundland",
    106: "Norfolk_terrier",
    107: "Norwegian_buhund",
    108: "Norwegian_elkhound",
    109: "Norwegian_lundehund",
    110: "Norwich_terrier",
    111: "Nova_scotia_duck_tolling_retriever",
    112: "Old_english_sheepdog",
    113: "Otterhound",
    114: "Papillon",
    115: "Parson_russell_terrier",
    116: "Pekingese",
    117: "Pembroke_welsh_corgi",
    118: "Petit_basset_griffon_vendeen",
    119: "Pharaoh_hound",
    120: "Plott",
    121: "Pointer",
    122: "Pomeranian",
    123: "Poodle",
    124: "Portuguese_water_dog",
    125: "Saint_bernard",
    126: "Silky_terrier",
    127: "Smooth_fox_terrier",
    128: "Tibetan_mastiff",
    129: "Welsh_springer_spaniel",
    130: "Wirehaired_pointing_griffon",
    131: "Xoloitzcuintli",
    132: "Yorkshire_terrier",
}
