# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service/service_spec/ObjectDetection_ImageRecon.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='service/service_spec/ObjectDetection_ImageRecon.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n5service/service_spec/ObjectDetection_ImageRecon.proto\"h\n\x15ObjDetImgReconRequest\x12\x14\n\x0cmodel_detect\x18\x01 \x01(\t\x12\x13\n\x0bmodel_recon\x18\x02 \x01(\t\x12\x10\n\x08img_path\x18\x03 \x01(\t\x12\x12\n\nconfidence\x18\x04 \x01(\t\"g\n\x06Result\x12\x12\n\ndelta_time\x18\x01 \x01(\t\x12\r\n\x05\x62oxes\x18\x02 \x01(\t\x12\x13\n\x0b\x63onfidences\x18\x03 \x01(\t\x12\x11\n\tclass_ids\x18\x04 \x01(\t\x12\x12\n\ntop_1_list\x18\x05 \x01(\t2@\n\x0b\x44\x65tectRecon\x12\x31\n\x0c\x64\x65tect_recon\x12\x16.ObjDetImgReconRequest\x1a\x07.Result\"\x00\x62\x06proto3')
)




_OBJDETIMGRECONREQUEST = _descriptor.Descriptor(
  name='ObjDetImgReconRequest',
  full_name='ObjDetImgReconRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='model_detect', full_name='ObjDetImgReconRequest.model_detect', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='model_recon', full_name='ObjDetImgReconRequest.model_recon', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='img_path', full_name='ObjDetImgReconRequest.img_path', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='confidence', full_name='ObjDetImgReconRequest.confidence', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=161,
)


_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='delta_time', full_name='Result.delta_time', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='boxes', full_name='Result.boxes', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='confidences', full_name='Result.confidences', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='class_ids', full_name='Result.class_ids', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='top_1_list', full_name='Result.top_1_list', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=163,
  serialized_end=266,
)

DESCRIPTOR.message_types_by_name['ObjDetImgReconRequest'] = _OBJDETIMGRECONREQUEST
DESCRIPTOR.message_types_by_name['Result'] = _RESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ObjDetImgReconRequest = _reflection.GeneratedProtocolMessageType('ObjDetImgReconRequest', (_message.Message,), dict(
  DESCRIPTOR = _OBJDETIMGRECONREQUEST,
  __module__ = 'service.service_spec.ObjectDetection_ImageRecon_pb2'
  # @@protoc_insertion_point(class_scope:ObjDetImgReconRequest)
  ))
_sym_db.RegisterMessage(ObjDetImgReconRequest)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), dict(
  DESCRIPTOR = _RESULT,
  __module__ = 'service.service_spec.ObjectDetection_ImageRecon_pb2'
  # @@protoc_insertion_point(class_scope:Result)
  ))
_sym_db.RegisterMessage(Result)



_DETECTRECON = _descriptor.ServiceDescriptor(
  name='DetectRecon',
  full_name='DetectRecon',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=268,
  serialized_end=332,
  methods=[
  _descriptor.MethodDescriptor(
    name='detect_recon',
    full_name='DetectRecon.detect_recon',
    index=0,
    containing_service=None,
    input_type=_OBJDETIMGRECONREQUEST,
    output_type=_RESULT,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DETECTRECON)

DESCRIPTOR.services_by_name['DetectRecon'] = _DETECTRECON

# @@protoc_insertion_point(module_scope)
