# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service/model/image_recon.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='service/model/image_recon.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x1fservice/model/image_recon.proto\"4\n\x11ImageReconRequest\x12\r\n\x05model\x18\x01 \x01(\t\x12\x10\n\x08img_path\x18\x02 \x01(\t\"+\n\x06Result\x12\x12\n\ndelta_time\x18\x01 \x01(\t\x12\r\n\x05top_5\x18\x02 \x01(\t23\n\x07\x46lowers\x12(\n\x07\x66lowers\x12\x12.ImageReconRequest\x1a\x07.Result\"\x00\x32-\n\x04\x44ogs\x12%\n\x04\x64ogs\x12\x12.ImageReconRequest\x1a\x07.Result\"\x00\x32-\n\x04\x43\x61rs\x12%\n\x04\x63\x61rs\x12\x12.ImageReconRequest\x1a\x07.Result\"\x00\x62\x06proto3')
)




_IMAGERECONREQUEST = _descriptor.Descriptor(
  name='ImageReconRequest',
  full_name='ImageReconRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='model', full_name='ImageReconRequest.model', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='img_path', full_name='ImageReconRequest.img_path', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=87,
)


_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='delta_time', full_name='Result.delta_time', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='top_5', full_name='Result.top_5', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=132,
)

DESCRIPTOR.message_types_by_name['ImageReconRequest'] = _IMAGERECONREQUEST
DESCRIPTOR.message_types_by_name['Result'] = _RESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ImageReconRequest = _reflection.GeneratedProtocolMessageType('ImageReconRequest', (_message.Message,), dict(
  DESCRIPTOR = _IMAGERECONREQUEST,
  __module__ = 'service.model.image_recon_pb2'
  # @@protoc_insertion_point(class_scope:ImageReconRequest)
  ))
_sym_db.RegisterMessage(ImageReconRequest)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), dict(
  DESCRIPTOR = _RESULT,
  __module__ = 'service.model.image_recon_pb2'
  # @@protoc_insertion_point(class_scope:Result)
  ))
_sym_db.RegisterMessage(Result)



_FLOWERS = _descriptor.ServiceDescriptor(
  name='Flowers',
  full_name='Flowers',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=134,
  serialized_end=185,
  methods=[
  _descriptor.MethodDescriptor(
    name='flowers',
    full_name='Flowers.flowers',
    index=0,
    containing_service=None,
    input_type=_IMAGERECONREQUEST,
    output_type=_RESULT,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FLOWERS)

DESCRIPTOR.services_by_name['Flowers'] = _FLOWERS


_DOGS = _descriptor.ServiceDescriptor(
  name='Dogs',
  full_name='Dogs',
  file=DESCRIPTOR,
  index=1,
  options=None,
  serialized_start=187,
  serialized_end=232,
  methods=[
  _descriptor.MethodDescriptor(
    name='dogs',
    full_name='Dogs.dogs',
    index=0,
    containing_service=None,
    input_type=_IMAGERECONREQUEST,
    output_type=_RESULT,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DOGS)

DESCRIPTOR.services_by_name['Dogs'] = _DOGS


_CARS = _descriptor.ServiceDescriptor(
  name='Cars',
  full_name='Cars',
  file=DESCRIPTOR,
  index=2,
  options=None,
  serialized_start=234,
  serialized_end=279,
  methods=[
  _descriptor.MethodDescriptor(
    name='cars',
    full_name='Cars.cars',
    index=0,
    containing_service=None,
    input_type=_IMAGERECONREQUEST,
    output_type=_RESULT,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CARS)

DESCRIPTOR.services_by_name['Cars'] = _CARS

# @@protoc_insertion_point(module_scope)
